# Glosario temático de las academias de la ESCOM IPN.
#
# Cada academia tiene:
#   - "academia": nombre que se muestra en el frontend.
#   - "carreras": carreras de la ESCOM donde el área es más común
#                 (ISC = Ing. en Sistemas Computacionales,
#                  IIA = Ing. en Inteligencia Artificial,
#                  LCD = Lic. en Ciencia de Datos).
#   - "descripcion": resumen general del área.
#   - "temas": frases cortas que describen temas típicos de protocolos de TT.
#
# El modelo compara cada fragmento del protocolo contra la descripción y cada
# tema por separado, así que conviene que los temas sean frases concretas
# (una idea por frase) en lugar de listas largas de palabras sueltas.

ACADEMIAS_ESCOM = [
    {
        "academia": "Ingeniería de Software",
        "carreras": ["ISC"],
        "descripcion": "Metodologías de desarrollo, arquitectura de software, calidad, patrones de diseño y gestión de proyectos de software.",
        "temas": [
            "Metodologías ágiles de desarrollo como Scrum, Kanban y XP",
            "Metodologías tradicionales, modelo en cascada, RUP y ciclo de vida del software",
            "Análisis y especificación de requerimientos funcionales y no funcionales",
            "Modelado con UML, diagramas de casos de uso, clases y secuencia",
            "Arquitectura de software, microservicios, arquitectura en capas y MVC",
            "Patrones de diseño y principios SOLID",
            "Pruebas de software unitarias, de integración y de aceptación",
            "Calidad del software, métricas, normas ISO y modelos de madurez CMMI",
            "Integración y despliegue continuo, DevOps y control de versiones",
            "Estimación de costos, planeación y administración de proyectos de software",
            "Mantenimiento, refactorización y reingeniería de sistemas heredados",
        ],
    },
    {
        "academia": "Sistemas Móviles y Web",
        "carreras": ["ISC"],
        "descripcion": "Desarrollo de aplicaciones móviles y plataformas web, servicios en línea y APIs.",
        "temas": [
            "Aplicación móvil para Android desarrollada en Kotlin o Java",
            "Aplicación móvil para iOS desarrollada en Swift",
            "Aplicaciones multiplataforma con Flutter o React Native",
            "Aplicación web con frontend en React, Angular o Vue",
            "Backend web con Node.js, PHP, Django o Spring y servicios API REST",
            "Geolocalización, mapas, GPS y servicios basados en ubicación",
            "Notificaciones push y sincronización de datos en dispositivos móviles",
            "Plataforma web para gestión, reservaciones, citas o comercio electrónico",
            "Diseño web responsivo y aplicaciones web progresivas",
            "Sistema web de control administrativo para una empresa o institución",
        ],
    },
    {
        "academia": "Bases de Datos y Sistemas de Información",
        "carreras": ["ISC", "LCD"],
        "descripcion": "Diseño y administración de bases de datos y sistemas de información para organizaciones.",
        "temas": [
            "Diseño de bases de datos relacionales, modelo entidad-relación y normalización",
            "Bases de datos NoSQL como MongoDB, Cassandra o Redis",
            "Consultas SQL, procedimientos almacenados y optimización de consultas",
            "Almacenes de datos, data warehouse y procesos ETL",
            "Sistema de información para control de inventarios, ventas o recursos humanos",
            "Administración, respaldo, replicación y seguridad de bases de datos",
            "Expediente clínico electrónico y sistemas de información hospitalaria",
            "Digitalización y gestión documental de procesos administrativos",
        ],
    },
    {
        "academia": "Sistemas Distribuidos",
        "carreras": ["ISC"],
        "descripcion": "Redes de computadoras, cómputo en la nube, sistemas operativos y protocolos de comunicación.",
        "temas": [
            "Redes de computadoras, modelo OSI, TCP/IP y enrutamiento",
            "Cómputo en la nube con AWS, Azure o Google Cloud",
            "Contenedores Docker, orquestación con Kubernetes y virtualización",
            "Sistemas distribuidos, tolerancia a fallas, consenso y replicación",
            "Cómputo paralelo y de alto rendimiento, GPU, MPI y OpenMP",
            "Sistemas operativos, procesos, hilos, planificación y concurrencia",
            "Redes inalámbricas, redes 5G, redes definidas por software",
            "Protocolos de comunicación y arquitectura cliente-servidor",
            "Blockchain y cadenas de bloques como sistema distribuido",
            "Balanceo de carga, escalabilidad y monitoreo de servidores",
        ],
    },
    {
        "academia": "Ciberseguridad y Criptografía",
        "carreras": ["ISC"],
        "descripcion": "Seguridad de la información, criptografía, protección de sistemas y análisis de amenazas.",
        "temas": [
            "Criptografía simétrica y asimétrica, RSA, AES y curvas elípticas",
            "Firmas digitales, certificados y infraestructura de llave pública",
            "Pruebas de penetración y hacking ético",
            "Detección de intrusos, malware y análisis forense digital",
            "Autenticación, control de acceso y autenticación multifactor",
            "Seguridad en aplicaciones web y vulnerabilidades OWASP",
            "Esteganografía y ocultamiento de información",
            "Privacidad y protección de datos personales",
            "Criptografía poscuántica y protocolos seguros",
        ],
    },
    {
        "academia": "Sistemas Digitales y Microelectrónica",
        "carreras": ["ISC"],
        "descripcion": "Sistemas embebidos, Internet de las Cosas, microcontroladores y arquitectura de computadoras.",
        "temas": [
            "Sistemas embebidos con microcontroladores Arduino, ESP32 o PIC",
            "Internet de las Cosas, sensores y dispositivos conectados",
            "Diseño de circuitos digitales en FPGA con VHDL o Verilog",
            "Arquitectura de computadoras y organización del procesador",
            "Adquisición de datos con sensores y actuadores",
            "Raspberry Pi y sistemas embebidos con Linux",
            "Domótica, casas inteligentes y automatización",
            "Dispositivos portátiles, wearables y monitoreo de signos vitales",
            "Procesamiento digital de señales en hardware",
            "Comunicación inalámbrica Bluetooth, LoRa y Zigbee",
        ],
    },
    {
        "academia": "Ciencias de la Computación",
        "carreras": ["ISC", "IIA"],
        "descripcion": "Algoritmos, estructuras de datos, teoría de la computación, optimización y matemáticas discretas.",
        "temas": [
            "Análisis y diseño de algoritmos y complejidad computacional",
            "Estructuras de datos avanzadas",
            "Teoría de grafos y algoritmos de rutas más cortas",
            "Teoría de la computación, autómatas y lenguajes formales",
            "Diseño de compiladores e intérpretes",
            "Optimización combinatoria, programación lineal y heurísticas",
            "Métodos numéricos y simulación computacional",
            "Computación cuántica y algoritmos cuánticos",
            "Problemas de calendarización, asignación y ruteo de vehículos",
        ],
    },
    {
        "academia": "Computación Gráfica, Videojuegos y Realidad Extendida",
        "carreras": ["ISC"],
        "descripcion": "Gráficos por computadora, desarrollo de videojuegos, realidad virtual y realidad aumentada.",
        "temas": [
            "Desarrollo de videojuegos con Unity o Unreal Engine",
            "Realidad virtual y entornos inmersivos",
            "Realidad aumentada en dispositivos móviles",
            "Modelado y animación 3D",
            "Renderizado, shaders y OpenGL",
            "Simuladores y entornos virtuales de entrenamiento",
            "Videojuegos serios y gamificación para la educación",
        ],
    },
    {
        "academia": "Interacción Humano-Computadora y Tecnología Educativa",
        "carreras": ["ISC", "IIA"],
        "descripcion": "Usabilidad, experiencia de usuario, accesibilidad y tecnologías para la enseñanza y el aprendizaje.",
        "temas": [
            "Diseño de experiencia de usuario y usabilidad",
            "Accesibilidad para personas con discapacidad visual, auditiva o motriz",
            "Traducción de lengua de señas y tecnologías de apoyo",
            "Plataformas de aprendizaje en línea y educación a distancia",
            "Sistemas tutores inteligentes y aprendizaje adaptativo",
            "Interfaces de voz, gestos y comunicación aumentativa",
            "Evaluación de interfaces con usuarios y pruebas de usabilidad",
        ],
    },
    {
        "academia": "Proyectos Estratégicos y Toma de Decisiones",
        "carreras": ["ISC", "LCD"],
        "descripcion": "Sistemas de apoyo a la toma de decisiones, inteligencia de negocios, gestión de procesos y emprendimiento tecnológico.",
        "temas": [
            "Sistemas de apoyo a la toma de decisiones",
            "Inteligencia de negocios, tableros e indicadores clave de desempeño",
            "Sistemas de planeación de recursos empresariales ERP y CRM",
            "Modelado y mejora de procesos de negocio",
            "Planeación estratégica, gobierno de TI e ITIL",
            "Emprendimiento tecnológico, modelo de negocio y estudio de mercado",
            "Evaluación financiera y análisis de costo-beneficio de proyectos",
            "Cadena de suministro y logística",
        ],
    },
    {
        "academia": "Inteligencia Artificial",
        "carreras": ["IIA", "ISC"],
        "descripcion": "Aprendizaje automático, redes neuronales, aprendizaje profundo, sistemas inteligentes y algoritmos bioinspirados.",
        "temas": [
            "Aprendizaje automático supervisado y no supervisado",
            "Redes neuronales artificiales y aprendizaje profundo",
            "Clasificación y regresión con árboles de decisión, SVM y random forest",
            "Algoritmos genéticos, evolutivos y optimización por enjambre",
            "Sistemas expertos, lógica difusa y representación del conocimiento",
            "Aprendizaje por refuerzo y agentes inteligentes",
            "Modelos generativos, redes generativas adversarias y modelos de difusión",
            "Sistemas de recomendación",
            "Explicabilidad, ética y sesgos en inteligencia artificial",
            "Entrenamiento de modelos con TensorFlow, PyTorch o scikit-learn",
        ],
    },
    {
        "academia": "Visión Artificial y Procesamiento de Imágenes",
        "carreras": ["IIA", "ISC"],
        "descripcion": "Análisis de imágenes y video, reconocimiento de patrones visuales y visión por computadora.",
        "temas": [
            "Detección y reconocimiento de objetos en imágenes con YOLO o redes convolucionales",
            "Reconocimiento facial y biometría",
            "Segmentación de imágenes médicas, radiografías y resonancias",
            "Procesamiento digital de imágenes, filtros y extracción de características",
            "Análisis de video, seguimiento de objetos y videovigilancia",
            "Reconocimiento óptico de caracteres OCR",
            "Estimación de pose y reconocimiento de gestos",
            "Detección de enfermedades en cultivos o plantas mediante imágenes",
            "Reconstrucción 3D y visión estereoscópica",
        ],
    },
    {
        "academia": "Procesamiento de Lenguaje Natural",
        "carreras": ["IIA", "LCD"],
        "descripcion": "Análisis y generación de texto y voz, modelos de lenguaje y comprensión del lenguaje humano.",
        "temas": [
            "Procesamiento de lenguaje natural y análisis de texto",
            "Chatbots y asistentes conversacionales",
            "Modelos de lenguaje grandes, transformers y BERT",
            "Análisis de sentimientos y minería de opiniones en redes sociales",
            "Clasificación de documentos y extracción de información",
            "Reconocimiento y síntesis de voz",
            "Traducción automática y lenguas indígenas",
            "Resumen automático de textos y generación de lenguaje",
            "Detección de noticias falsas, discurso de odio o plagio",
        ],
    },
    {
        "academia": "Robótica y Sistemas Autónomos",
        "carreras": ["IIA", "ISC"],
        "descripcion": "Robots, vehículos autónomos, control inteligente y navegación.",
        "temas": [
            "Robots móviles, navegación autónoma y planeación de trayectorias",
            "Localización y mapeo simultáneo SLAM",
            "Brazos robóticos, cinemática y control de manipuladores",
            "Drones y vehículos aéreos no tripulados",
            "Vehículos autónomos y sistemas de asistencia al conductor",
            "Sistemas de control PID y control inteligente",
            "Robot Operating System ROS y simulación robótica",
            "Robótica de servicio, asistencial y educativa",
        ],
    },
    {
        "academia": "Ciencia de Datos y Analítica",
        "carreras": ["LCD", "IIA"],
        "descripcion": "Extracción de conocimiento a partir de datos, big data, minería de datos y visualización.",
        "temas": [
            "Análisis exploratorio, limpieza y preprocesamiento de datos",
            "Minería de datos, reglas de asociación y agrupamiento",
            "Big data con Hadoop, Spark y procesamiento de grandes volúmenes de datos",
            "Visualización de datos y tableros interactivos",
            "Análisis predictivo para la toma de decisiones",
            "Análisis de datos de salud, epidemiología o datos abiertos de gobierno",
            "Análisis de redes sociales y ciencia de redes",
            "Ingeniería de datos y canalizaciones de datos",
            "Detección de anomalías y fraudes",
            "Análisis de datos geoespaciales",
        ],
    },
    {
        "academia": "Estadística y Modelado Matemático",
        "carreras": ["LCD"],
        "descripcion": "Métodos estadísticos, probabilidad, modelos matemáticos y pronóstico.",
        "temas": [
            "Inferencia estadística, pruebas de hipótesis e intervalos de confianza",
            "Modelos de regresión lineal, logística y modelos lineales generalizados",
            "Series de tiempo y pronóstico con ARIMA",
            "Estadística bayesiana y modelos probabilísticos",
            "Diseño de experimentos y muestreo",
            "Análisis multivariado y reducción de dimensionalidad",
            "Simulación Monte Carlo y procesos estocásticos",
            "Modelos matemáticos epidemiológicos, financieros o actuariales",
        ],
    },
]
